### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hkauroberoi** [andela-mnzomo/project-dream-team-three#1]
What a wonderful project. I have started working on flask (python) recently and referring to your code for my college project. While all the requirements are met, I face the following error and unable to fix the same. I use PYCHARM x64 version on windows 10 with Python 3.6.4.

Traceback (most recent call last):
  File "C:/Users/xxxxx/PycharmProjects/xxx/venv/run.py", line 6, in <module>
    app = create_app(config_name)
  File "C:\Users\xxxxx\PycharmProjects\xxx\venv\app\__init__.py", line 17, in create_app
    app.config.from_object(app_config[config_name])
KeyError: None

Process finished with exit code 1

**Comment by oumao** [comment]
I too have this problem. But Once I debug it out I will be able to tell the way forward.

**Comment by oumao** [comment]
So I found out that actually the problem occurs when setting FLASK_ENV or FLASK_CONFIG.

In windows, suppose you use either:

*set FLASK_CONFIG=development* or *set FLASK_ENV=development* 

Then in your run.py file you must specify based on the way you named your environment:

#run.py

import os
from app import create_app

app = create_app(os.getenv("FLASK_ENV")) or app = create_app(os.getenv("FLASK_CONFIG"))

if __name__ == '__main__':
    app.run()
